name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Create uv venv
        run: uv venv

      - name: Install nox and ruff
        run: uv pip install nox ruff

      - name: Run ruff linter via nox session
        run: uv run nox -s lint
