# This workflow will install Python dependencies, run tests for a range of Python versions

name: tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Create uv venv
      run: uv venv

    - name: Install nox
      run: uv pip install nox

    - name: Test with nox and pytest
      run: uv run nox -s tests
